kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-volume-claim
spec:
  storageClassName: ""
  volumeName: config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
  selector:
    matchLabels:
      config-init: config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
  labels:
      config-init: config
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/config/db"
