apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"

---

apiVersion: batch/v1
kind: Job
metadata:
  name: config-init-load
spec:
  template:
    metadata:
      labels:
        app: config-init-load
    spec:
      restartPolicy: Never
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-volume-claim
      containers:
        - name: config-init-load
          image: gluufederation/config-init:3.1.6_03
          volumeMounts:
            - mountPath: /opt/config-init/db
              name: config
              subPath: db
          envFrom:
          - configMapRef:
              name: config-cm
          args: ["load"]
