apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    name: elastic
    targetPort: 9200
    protocol: TCP
  - port: 9300
    name: elastic-cluster
    targetPort: 9300
    protocol: TCP
  selector:
    app: elasticsearch
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        imagePullPolicy: Always
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        ports:
        - containerPort: 9200
          name: elastic
        - containerPort: 9300
          name: elastic-cluster
        env:
          - name: cluster.name
            value: "gluu-cluster"
          - name: bootstrap.memory_lock
            value: "false"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: TAKE_FILE_OWNERSHIP
            value: "true"
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elasticsearch-data
        hostPath:
          path: /data/elasticsearch/data
          type: DirectoryOrCreate
