kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-shib-volume-claim
spec:
  storageClassName: oxtrust-gluu
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
