version: "3.3"

networks:
  gluu:
    external: true

services:
  redis:
    image: redis:alpine
    networks:
      gluu:
        aliases:
          - redis.server
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == worker
