version: "3.7"

networks:
  gluu:
    external: true

services:
  consul:
    image: consul
    # will be used as consul node name (alphanum and dash only)
    hostname: "consul-{{.Node.Hostname}}"
    command: "agent -server -retry-join consul.server -client 0.0.0.0"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={
          "leave_on_terminate": true,
          "skip_leave_on_interrupt": true,
          "autopilot": {
            "cleanup_dead_servers": true
          },
          "bootstrap_expect": 2,
          "disable_update_check": true,
          "disable_host_node_id": true
        }'
    networks:
      gluu:
        aliases:
          - consul.server
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    volumes:
      - /opt/consul:/consul/data
    labels:
      - "SERVICE_IGNORE=yes"
