version: "3.3"

networks:
  gluu:
    external: true

services:
  ldap_peer:
    image: gluufederation/opendj:3.1.2_dev
    environment:
      - GLUU_LDAP_INIT=false
      - GLUU_LDAP_ADDR_INTERFACE=eth0
      - GLUU_KV_HOST=consul.server
    networks:
      gluu:
        aliases:
          - ldap.server
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == worker
    volumes:
      - /opt/opendj/config:/opt/opendj/config
      - /opt/opendj/ldif:/opt/opendj/ldif
      - /opt/opendj/db:/opt/opendj/db
