version: "3.7"

networks:
  gluu:
    external: true

services:
  ldap_manager:
    image: gluufederation/opendj:3.1.6_02
    hostname: ldap.manager
    environment:
      - GLUU_LDAP_INIT=true
      - GLUU_LDAP_INIT_HOST=ldap.server
      - GLUU_CACHE_TYPE=NATIVE_PERSISTENCE
      - GLUU_CONFIG_CONSUL_HOST=consul.server
      - GLUU_CONFIG_CONSUL_CONSISTENCY=default
      - GLUU_SECRET_VAULT_HOST=vault.server
      - GLUU_OXTRUST_CONFIG_GENERATION=true
      - GLUU_LDAP_ADVERTISE_ADDR=ldap.manager
      # - GLUU_CACHE_TYPE=REDIS  # don't forget to enable redis service
      # - GLUU_REDIS_URL=redis:6379
      # - GLUU_REDIS_TYPE=STANDALONE
      # the value must match network alias `ldap.server` because other containers
      # use this value as LDAP hostname
      - GLUU_CERT_ALT_NAME=ldap.server
    networks:
      gluu:
        aliases:
          - ldap.manager
          - ldap.server
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.hostname == manager
    volumes:
      - /opt/opendj/db:/opt/opendj/db
      - /opt/opendj/config:/opt/opendj/config
      - /opt/opendj/ldif:/opt/opendj/ldif
      - /opt/opendj/logs:/opt/opendj/logs
      - /opt/opendj/backup:/opt/opendj/bak
      - /opt/opendj/flag:/flag
    labels:
      - "SERVICE_IGNORE=yes"
    secrets:
      - source: vault_role_id
        target: /etc/certs/vault_role_id
      - source: vault_secret_id
        target: /etc/certs/vault_secret_id

secrets:
  vault_role_id:
    external: true
  vault_secret_id:
    external: true
