version: "3.3"

networks:
  gluu:
    external: true

services:
  ldap_manager:
    image: gluufederation/opendj:latest
    hostname: ldap.manager
    environment:
      - GLUU_LDAP_INIT=true
      - GLUU_LDAP_INIT_HOST=ldap.server
      - GLUU_CACHE_TYPE=REDIS
      - GLUU_REDIS_URL=${GLUU_REDIS_URL}
      - GLUU_REDIS_TYPE=CLUSTER
      - GLUU_CONFIG_ADAPTER=consul
      - GLUU_CONSUL_HOST=consul.server
      - GLUU_OXTRUST_CONFIG_GENERATION=true
      - GLUU_LDAP_ADDR_INTERFACE=eth0
      - GLUU_LDAP_ADVERTISE_ADDR=ldap.manager
    networks:
      gluu:
        aliases:
          - ldap.manager
          - ldap.server
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.hostname == manager
    volumes:
      - /opt/opendj/db:/opt/opendj/db
      - /opt/opendj/config:/opt/opendj/config
      - /opt/opendj/ldif:/opt/opendj/ldif
      - /opt/opendj/logs:/opt/opendj/logs
      - /opt/opendj/flag:/flag
    labels:
      - "SERVICE_IGNORE=yes"
