version: "3.3"

networks:
  gluu:
    external: true

services:
  ldap_init:
    image: gluufederation/opendj:3.1.2_dev
    environment:
      - GLUU_LDAP_INIT=true
      - GLUU_LDAP_INIT_HOST=ldap.server
      - GLUU_LDAP_ADDR_INTERFACE=eth0
      - GLUU_KV_HOST=consul.server
      - GLUU_CACHE_TYPE=REDIS
      - GLUU_REDIS_URL=redis.server:6379
      - GLUU_OXTRUST_CONFIG_GENERATION=true
    networks:
      gluu:
        aliases:
          - ldap.server
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == manager
