version: "3.3"

networks:
  gluu:
    external: true

services:
  nginx:
    image: gluufederation/nginx:3.1.2_dev
    environment:
      - GLUU_OXAUTH_BACKEND=oxauth.server:8080
      - GLUU_OXTRUST_BACKEND=oxtrust.server:8080
      - GLUU_KV_HOST=consul.server
    networks:
      gluu:
        aliases:
          - nginx.server
          - ${DOMAIN}
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
