version: "3.3"

networks:
  gluu:
    external: true

services:
  nginx:
    image: gluufederation/nginx:3.1.2_dev
    environment:
      - GLUU_OXAUTH_BACKEND=traefik:80
      - GLUU_OXAUTH_HOST_HEADER=oxauth.gluu
      - GLUU_OXTRUST_BACKEND=traefik:80
      - GLUU_OXTRUST_HOST_HEADER=oxtrust.gluu
      - GLUU_KV_HOST=consul.server
      - GLUU_RESOLVER_ADDR=127.0.0.11
      - GLUU_OX_PROXY_MODE=true
    networks:
      gluu:
        aliases:
          - nginx.server
          - ${DOMAIN}
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
