version: "3.3"

networks:
  gluu:
    external: true

services:
  oxauth:
    image: gluufederation/oxauth:3.1.2_dev
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_KV_HOST=consul.server
    networks:
      gluu:
        aliases:
          - oxauth.server
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      labels:
        - "traefik.port=8080"
        - "traefik.backend=oxauth"
        - "traefik.frontend.rule=Host:oxauth.gluu"

  oxtrust:
    image: gluufederation/oxtrust:3.1.2_dev
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_KV_HOST=consul.server
    networks:
      gluu:
        aliases:
          - oxtrust.server
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.port=8080"
        - "traefik.backend=oxtrust"
        - "traefik.frontend.rule=Host:oxtrust.gluu"
