version: "3.3"

networks:
  gluu:
    external: true

services:
  oxpassport:
    image: gluufederation/oxpassport:3.1.2_dev
    environment:
      - GLUU_KV_HOST=consul.server
      - GLUU_LDAP_URL=ldap.server:1636
    networks:
      gluu:
        aliases:
          - oxpassport.server
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.port=8080"
        - "traefik.backend=oxpassport"
        - "traefik.frontend.rule=Host:oxpassport.gluu"
