version: "3.3"

networks:
  gluu:
    external: true

services:
  traefik:
    image: traefik
    command:
      - "--consul"
      - "--consul.endpoint=consul.server:8500"
      - "--consul.prefix=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gluu
    ports:
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
