version: "3.3"

networks:
  gluu:
    external: true

services:
  redis:
    image: redis:alpine
    # run cluster-enabled redis-server
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --appendonly yes --cluster-node-timeout 5000
    # volumes:
    #   - /opt/redis:/data
    networks:
      gluu:
        aliases:
          - redis.server
    deploy:
      replicas: 9
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    labels:
      - "SERVICE_IGNORE=yes"
      # - "SERVICE_NAME=redis"
      # - "SERVICE_6379_CHECK_TCP=true"
      # - "SERVICE_6379_CHECK_INTERVAL=15s"
