version: "3.7"

networks:
  gluu:
    external: true

services:
  registrator:
    image: gluufederation/registrator:dev
    command: -internal -cleanup -resync 30 -retry-attempts 5 -retry-interval 10 consul://consul.server:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      gluu:
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
