version: "3.3"

networks:
  gluu:
    external: true

services:
  twemproxy:
    image: perlmint/twemproxy
    volumes:
      - /root/nutcracker.yml:/etc/twemproxy/conf.yml
    networks:
      gluu:
        aliases:
          - twemproxy.server
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    labels:
      - "SERVICE_IGNORE=yes"
