version: "3.3"

networks:
  gluu:
    external: true

services:
  oxauth:
    image: gluufederation/oxauth:3.1.2_dev
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_KV_HOST=consul.server
    networks:
      gluu:
        aliases:
          - oxauth.server
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1536M

  oxtrust:
    image: gluufederation/oxtrust:3.1.2_dev
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_KV_HOST=consul.server
    networks:
      gluu:
        aliases:
          - oxtrust.server
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1536M
      labels:
        - "traefik.port=8080"
        - "traefik.backend=oxtrust"
        - "traefik.frontend.rule=Host:oxtrust.gluu"
        - "traefik.backend.loadbalancer.stickiness=true"
    volumes:
      - /opt/shared-shibboleth-idp:/opt/shared-shibboleth-idp

  oxshibboleth:
    image: gluufederation/oxshibboleth:3.1.2_dev
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_KV_HOST=consul.server
    networks:
      gluu:
        aliases:
          - oxshibboleth.server
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1536M
      labels:
        - "traefik.port=8080"
        - "traefik.backend=oxshibboleth"
        - "traefik.frontend.rule=Host:oxshibboleth.gluu"
        - "traefik.backend.loadbalancer.stickiness=true"
    volumes:
      - /opt/shared-shibboleth-idp:/opt/shared-shibboleth-idp

  oxpassport:
    image: gluufederation/oxpassport:3.1.2_dev
    environment:
      - GLUU_KV_HOST=consul.server
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_OXAUTH_BACKEND=oxauth.server:8080
      - GLUU_OXTRUST_BACKEND=oxtrust.server:8080
    networks:
      gluu:
        aliases:
          - oxpassport.server
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s

  nginx:
    image: gluufederation/nginx:3.1.2_dev
    environment:
      - GLUU_KV_HOST=consul.server

      # ==========================================================
      # the following lines are used when resolver mode is enabled
      # note we're using traefik to proxy ox apps
      # ==========================================================
      - GLUU_OXAUTH_BACKEND=oxauth.server:8080
      # - GLUU_OXAUTH_HOST_HEADER=oxauth.gluu:8080
      - GLUU_OXTRUST_BACKEND=traefik
      - GLUU_OXTRUST_HOST_HEADER=oxtrust.gluu:8080
      - GLUU_OXSHIBBOLETH_BACKEND=traefik
      - GLUU_OXSHIBBOLETH_HOST_HEADER=oxshibboleth.gluu:8080
      - GLUU_OXPASSPORT_BACKEND=oxpassport.server:8090
      # - GLUU_OXPASSPORT_HOST_HEADER=oxpassport.gluu:8090
      - GLUU_PROXY_MODE=resolver
      - GLUU_RESOLVER_ADDR=127.0.0.11

      # ==========================================================
      # the following lines are used when resolver mode is enabled
      # note we're using native swarm routing to proxy ox apps
      # ==========================================================
      # - GLUU_OXAUTH_BACKEND=oxauth.server:8080
      # - GLUU_OXTRUST_BACKEND=oxtrust.server:8080
      # - GLUU_OXTRUST_HOST_HEADER=oxtrust.server:8080
      # - GLUU_OXSHIBBOLETH_BACKEND=oxshibboleth.server:8080
      # - GLUU_OXPASSPORT_BACKEND=oxpassport.server:8090
      # - GLUU_PROXY_MODE=resolver
      # - GLUU_RESOLVER_ADDR=127.0.0.11
    networks:
      gluu:
        aliases:
          - nginx.server
          - ${DOMAIN}
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host

  gobetween:
    image: iromli/gobetween
    networks:
      gluu:
        aliases:
          - gobetween.server
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
