version: "3.3"

networks:
  gluu:
    external: true

services:
  oxauth:
    image: gluufederation/oxauth:latest
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_CONFIG_ADAPTER=consul
      - GLUU_CONSUL_HOST=consul.server
    networks:
      gluu:
        aliases:
          - oxauth.server
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1536M
    labels:
      - "SERVICE_NAME=oxauth"
      - "SERVICE_8080_CHECK_HTTP=/oxauth/.well-known/openid-configuration"
      - "SERVICE_8080_CHECK_INTERVAL=15s"
      - "SERVICE_8080_CHECK_TIMEOUT=5s"

  oxtrust:
    image: gluufederation/oxtrust:latest
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_CONFIG_ADAPTER=consul
      - GLUU_CONSUL_HOST=consul.server
      - GLUU_OXAUTH_BACKEND=oxauth.server:8080
    networks:
      gluu:
        aliases:
          - oxtrust.server
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1536M
    volumes:
      - /opt/shared-shibboleth-idp:/opt/shared-shibboleth-idp
    labels:
      - "SERVICE_NAME=oxtrust"
      - "SERVICE_8080_CHECK_HTTP=/identity/restv1/scim-configuration"
      - "SERVICE_8080_CHECK_INTERVAL=15s"
      - "SERVICE_8080_CHECK_TIMEOUT=5s"

  oxshibboleth:
    image: gluufederation/oxshibboleth:latest
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_CONFIG_ADAPTER=consul
      - GLUU_CONSUL_HOST=consul.server
    networks:
      gluu:
        aliases:
          - oxshibboleth.server
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1536M
    volumes:
      - /opt/shared-shibboleth-idp:/opt/shared-shibboleth-idp
    labels:
      - "SERVICE_NAME=oxshibboleth"
      - "SERVICE_8086_CHECK_HTTP=/idp"
      - "SERVICE_8086_CHECK_INTERVAL=15s"
      - "SERVICE_8086_CHECK_TIMEOUT=5s"

  oxpassport:
    image: gluufederation/oxpassport:latest
    environment:
      - GLUU_CONFIG_ADAPTER=consul
      - GLUU_CONSUL_HOST=consul.server
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_OXAUTH_BACKEND=oxauth.server:8080
      - GLUU_OXTRUST_BACKEND=oxtrust.server:8080
    networks:
      gluu:
        aliases:
          - oxpassport.server
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    labels:
      - "SERVICE_NAME=oxpassport"
      - "SERVICE_8090_CHECK_HTTP=/passport"
      - "SERVICE_8090_CHECK_INTERVAL=15s"
      - "SERVICE_8090_CHECK_TIMEOUT=5s"

  nginx:
    image: gluufederation/nginx:latest
    environment:
      - GLUU_CONFIG_ADAPTER=consul
      - GLUU_CONSUL_HOST=consul.server
      - GLUU_CONSUL_PORT=8500
    networks:
      gluu:
        aliases:
          - nginx.server
          - ${DOMAIN}
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    labels:
      - "SERVICE_IGNORE=yes"
