version: "3.7"

networks:
  gluu:
    external: true

services:
  oxauth:
    image: gluufederation/oxauth:3.1.6_01
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_CONFIG_CONSUL_HOST=consul.server
      - GLUU_SECRET_VAULT_HOST=vault.server
    networks:
      gluu:
        aliases:
          - oxauth.server
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1536M
    labels:
      - "SERVICE_NAME=oxauth"
      - "SERVICE_8080_CHECK_HTTP=/oxauth/.well-known/openid-configuration"
      - "SERVICE_8080_CHECK_INTERVAL=15s"
      - "SERVICE_8080_CHECK_TIMEOUT=5s"
    secrets:
      - source: vault_role_id
        target: /etc/certs/vault_role_id
      - source: vault_secret_id
        target: /etc/certs/vault_secret_id

  oxtrust:
    image: gluufederation/oxtrust:3.1.6_01
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_CONFIG_CONSUL_HOST=consul.server
      - GLUU_SECRET_VAULT_HOST=vault.server
      - GLUU_OXAUTH_BACKEND=oxauth.server:8080
    networks:
      gluu:
        aliases:
          - oxtrust.server
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1536M
    volumes:
      - /opt/shared-shibboleth-idp:/opt/shared-shibboleth-idp
    labels:
      - "SERVICE_NAME=oxtrust"
      - "SERVICE_8080_CHECK_HTTP=/identity/restv1/scim-configuration"
      - "SERVICE_8080_CHECK_INTERVAL=15s"
      - "SERVICE_8080_CHECK_TIMEOUT=5s"
      - "APP_NAME=oxtrust" # required for CacheRefresh
    secrets:
      - source: vault_role_id
        target: /etc/certs/vault_role_id
      - source: vault_secret_id
        target: /etc/certs/vault_secret_id

  oxshibboleth:
    image: gluufederation/oxshibboleth:3.1.6_01
    environment:
      - GLUU_LDAP_URL=ldap.server:1636
      - GLUU_CONFIG_CONSUL_HOST=consul.server
      - GLUU_SECRET_VAULT_HOST=vault.server
    networks:
      gluu:
        aliases:
          - oxshibboleth.server
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1536M
    volumes:
      - /opt/shared-shibboleth-idp:/opt/shared-shibboleth-idp
    labels:
      - "SERVICE_NAME=oxshibboleth"
      - "SERVICE_8086_CHECK_HTTP=/idp"
      - "SERVICE_8086_CHECK_INTERVAL=15s"
      - "SERVICE_8086_CHECK_TIMEOUT=5s"
    secrets:
      - source: vault_role_id
        target: /etc/certs/vault_role_id
      - source: vault_secret_id
        target: /etc/certs/vault_secret_id

  oxpassport:
    image: gluufederation/oxpassport:3.1.6_01
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul.server
      - GLUU_SECRET_VAULT_HOST=vault.server
    networks:
      gluu:
        aliases:
          - oxpassport.server
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    labels:
      - "SERVICE_NAME=oxpassport"
      - "SERVICE_8090_CHECK_HTTP=/passport"
      - "SERVICE_8090_CHECK_INTERVAL=15s"
      - "SERVICE_8090_CHECK_TIMEOUT=5s"
    secrets:
      - source: vault_role_id
        target: /etc/certs/vault_role_id
      - source: vault_secret_id
        target: /etc/certs/vault_secret_id

  nginx:
    image: gluufederation/nginx:3.1.6_01
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul.server
      - GLUU_SECRET_VAULT_HOST=vault.server
    networks:
      gluu:
        aliases:
          - nginx.server
          - ${DOMAIN}
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    labels:
      - "SERVICE_IGNORE=yes"
    secrets:
      - source: vault_role_id
        target: /etc/certs/vault_role_id
      - source: vault_secret_id
        target: /etc/certs/vault_secret_id

secrets:
  vault_role_id:
    external: true
  vault_secret_id:
    external: true
