kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gluu-role
  namespace: default
rules:
- apiGroups: [""] # "" refers to the core API group
  resources: ["configmaps", "secrets", "pods", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
