apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    # server: 10.11.241.63
    server: nfs-server.default.svc.cluster.local
    path: "/opt/shared-shibboleth-idp"
