apiVersion: v1
kind: PersistentVolume
metadata:
  name: opendj-init-pv
  labels:
    opendj: config
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID:
    fsType: ext4


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: opendj-repl-pv
  labels:
    opendj: repl
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID:
    fsType: ext4


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: opendj-volume-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gis
  selector:
    matchLabels:
      opendj: config

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: opendj-repl-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      opendj: repl