apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  labels:
      config-init: config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID:
    fsType: ext4
    
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-volume-claim
spec:
  storageClassName: ""
  volumeName: config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      config-init: config

---
