apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-shib-pv
  labels:
      shared-shib: main
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID:
    fsType: ext4

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-shib-volume-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      shared-shib: main
