kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-shib-volume-claim
spec:
  storageClassName: ""
  volumeName: shared-shib
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
  selector:
    matchLabels:
      shared-shib: shib

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-shib
  labels:
      shared-shib: shib
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/shared-shibboleth-idp"
